### ISSUE TITLE
Cannot edit nor use use template after upgrade to 3.1.1687383640

### ISSUE THREAD

**Issue by lshaw1968** [veda-consulting/uk.co.vedaconsulting.mosaico#605]
Hi, I cannot use or edit templates after update to new version.

Here what I see in console:
Uncaught TypeError: $.fn.button.noConflict is not a function
    at noConflict.js?r=rFjOgfr_CA:3:15
    at noConflict.js?r=rFjOgfr_CA:4:3
/fr/sites/default/files/civicrm/mosaico-template/versafix-1/template-versafix-1.html:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)

And here the log

Jul 24 11:58:00  [error] Expected one MessageTemplate but found 0

**Comment by MegaphoneJon** [comment]
Is it a version mismatch? What version of CiviCRM are you on?
